apiVersion: apps/v1
kind: Deployment
metadata:
  name: rf-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rf-model
  template:
    metadata:
      labels:
        app: rf-model
    spec:
      containers:
      - name: rf-container
        image: wohousekey/randomforest:latest
        command: ["sh", "-c", "python /app/randomForest.py && tail -f /dev/null"]
        ports:
        - containerPort: 80
